radar:
    dir: /Users/rijaf/Desktop/RADAR/DATA/ODIM_H5
    format_dir: '%Y%m%d'
    format_file: 'vol_%Y-%m-%d_%H-%M-%S.h5'
vp:
    dir: /Users/rijaf/Desktop/RADAR/biorad_vp/outputs
    sevip:
        missval: -99999
        lon: lon
        lat: lat
        time: time
class:
    dir: /Users/rijaf/Desktop/RADAR/classification/outputs
